### ISSUE TITLE
Native btrfs raid

### ISSUE THREAD

**Issue by LeoMeinel** [LeoMeinel/arch-install#1]
Find a way to use native btrfs raid instead of using mdadm!
This should improve performance and decrease "bloat" if you can call it that.

**Comment by LeoMeinel** [comment]
At the moment this doesn't seem to be possible since btrfs RAID doesn't create a block device.
However, if btrfs would implement native encryption this might be possible in the future.

**Comment by LeoMeinel** [comment]
Another idea I had is that btrfs could just use mdadm natively and implement a way for the raid and btrfs to interact.
I am not sure if that is planned.

**Comment by LeoMeinel** [comment]
I will close this since the chance of this getting implemented is very slim. Also mdadm works fine with btrfs

**Comment by leomeinel** [comment]
This will not be implemented
