### ISSUE TITLE
Add laptop specific packages

### ISSUE THREAD

**Issue by leomeinel** [leomeinel/arch-install#68]
- brightnessctl

**Comment by LeoMeinel** [comment]
`acpi` package may be needed, but as far as I can tell it is not!

**Comment by LeoMeinel** [comment]
I will mark this as solved because I think that kde ships laptop specific settings anyways.
I May reopen this when I have a laptop to test this in.

**Comment by leomeinel** [comment]
https://wiki.archlinux.org/title/laptop

**Comment by leomeinel** [comment]
This will only be an implementation for Lenovo laptops (Linux native laptops probably included). I can just hope that either System76, Tuxedocomputers or Lenovo come up with an AMD 7945hx/7940hs & 7600m/7700m combination until late August. Otherwise I'm screwed..

**Comment by leomeinel** [comment]
ASUS and Alienware are currently the only ones and their Linux support definetly isn't something I want to deal with. Their devices are also pretty ugly and way too much for me.

**Comment by leomeinel** [comment]
> This will only be an implementation for Lenovo laptops (Linux native laptops probably included). I can just hope that either System76, Tuxedocomputers or Lenovo come up with an AMD 7945hx/7940hs & 7600m/7700m combination until late August. Otherwise I'm screwed..

If that won't be the case, I'll most likely settle for a system without a discrete GPU. If I later need one I can still use the USB4 for discrete GPU docks.
Might also save me some battery so it's not the worst choice.

**Comment by leomeinel** [comment]
I'll postpone this until I have a laptop to actually test things on. Doesn't make much sense otherwise I guess.

**Comment by leomeinel** [comment]
https://wiki.archlinux.org/title/Laptop_Mode_Tools

**Comment by leomeinel** [comment]
https://wiki.archlinux.org/title/TLP

**Comment by leomeinel** [comment]
tlp is a very generic way to improve battery life on linux as far as I can tell. This seems to be the optimal way and should support a lot of systems!

**Comment by leomeinel** [comment]
It also doesn't necessarily require any additional configuration, which is perfect!
