### ISSUE TITLE
KDE: some windows don't maximize anymore

### ISSUE THREAD

**Issue by leomeinel** [leomeinel/arch-install#69]

**Comment by LeoMeinel** [comment]
![17-10-2022_19:44:41](https://user-images.githubusercontent.com/20671121/196246510-ae7a8195-9fcf-4720-9468-536f3ea4d0c7.png)

**Comment by LeoMeinel** [comment]
Maybe I can find a workaround

**Comment by LeoMeinel** [comment]
https://bugs.kde.org/show_bug.cgi?id=460628

**Comment by LeoMeinel** [comment]
Ignoring KWallet's Password popup (whatever application that is) might be an idea, if it is not ignored by default because it doesn't seem to maximize in the weird way it did before.

**Comment by LeoMeinel** [comment]
This bug applies to most gtk2/3 applications

**Comment by LeoMeinel** [comment]
# window-rule

![17-10-2022_19:44:41](https://user-images.githubusercontent.com/20671121/196673394-7402fc90-814e-4f3b-a6d0-b65c6862c18c.png)

# gtk3-noborder

![19-10-2022_12:28:23](https://user-images.githubusercontent.com/20671121/196673398-f92d78a6-062c-4213-b633-61628410cc3a.png)

# gtk3

![19-10-2022_12:29:16](https://user-images.githubusercontent.com/20671121/196673401-442e310c-bee9-4002-8214-c34a76c079e1.png)

# gtk2

![19-10-2022_12:44:16](https://user-images.githubusercontent.com/20671121/196673404-3ff08369-e6d4-4f59-b9ec-ffa41b6182a9.png)

**Comment by LeoMeinel** [comment]
https://github.com/KDE/kwin/commit/903e18d88c39c81bd05162fec1d536f6974c15e2
